@hostname = http://localhost:5000

### Crear un nuevo curso
POST {{hostname}}/course
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlMTdmNWYyMi1lOWRhLTQ4YTMtOTgxMy04YmEzNjk1YTJlODgiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGVzIjpbImFkbWluaXN0cmFkb3IiXSwiaWF0IjoxNzYyNzMzNzg5LCJleHAiOjE3NjI4MjAxODl9.BVhUrI-EwMBqZ--porOucVkeNj6Z0-htvAm45gep3tk

{
    "title": "Curso python Primeros pasos",
    "description": "Curso introductorio de python donde se vera la hisotrio el por qu y como funciona python "
}