@hostname = http://localhost:5000


### Crear una nueva leccion para un topico
POST {{hostname}}/lesson
Content-Type: application/json

{
  "title": "Historia de python",
  "order": 1,
  "description": "Historia desde el inicio y la creaciond de python",
  "resource_url": "https://pruebita.com",
  "topic_uuid": "c0916232-dd37-4ed0-bc57-e484ac5bd597"
}
