import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const GEIST_SANS = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const GEIST_MONO = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const METADATA: Metadata = {
  title: "Aprende",
  description: "Generated by create next app",
};

const ROOT_LAYOUT = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return (
    <html lang="en">
      <body
        className={`${GEIST_SANS.variable} ${GEIST_MONO.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
};
export default ROOT_LAYOUT;
